/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SoloRouteImport } from './routes/solo'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBoasVindasRouteImport } from './routes/_authenticated/boas-vindas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as SoloBoasVindasRouteImport } from './routes/solo.boas-vindas'
import { Route as SoloPerdcompRouteImport } from './routes/solo.perdcomp'
import { Route as AuthenticatedMensagensIndexRouteImport } from './routes/_authenticated/mensagens.index'
import { Route as AuthenticatedMensagensIdRouteImport } from './routes/_authenticated/mensagens.$id'
import { Route as AuthenticatedPerdcompIndexRouteImport } from './routes/_authenticated/perdcomp.index'
import { Route as SoloMensagensIndexRouteImport } from './routes/solo.mensagens.index'
import { Route as SoloMensagensIdRouteImport } from './routes/solo.mensagens.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloRoute = SoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoasVindasRoute = AuthenticatedBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SoloBoasVindasRoute = SoloBoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => SoloRoute,
} as any)
const SoloPerdcompRoute = SoloPerdcompRouteImport.update({
  id: '/perdcomp',
  path: '/perdcomp',
  getParentRoute: () => SoloRoute,
} as any)
const AuthenticatedMensagensIndexRoute =
  AuthenticatedMensagensIndexRouteImport.update({
    id: '/mensagens/',
    path: '/mensagens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensagensIdRoute =
  AuthenticatedMensagensIdRouteImport.update({
    id: '/mensagens/$id',
    path: '/mensagens/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerdcompIndexRoute =
  AuthenticatedPerdcompIndexRouteImport.update({
    id: '/perdcomp/',
    path: '/perdcomp/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const SoloMensagensIndexRoute = SoloMensagensIndexRouteImport.update({
  id: '/mensagens/',
  path: '/mensagens/',
  getParentRoute: () => SoloRoute,
} as any)
const SoloMensagensIdRoute = SoloMensagensIdRouteImport.update({
  id: '/mensagens/$id',
  path: '/mensagens/$id',
  getParentRoute: () => SoloRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/solo': typeof SoloRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/solo/boas-vindas': typeof SoloBoasVindasRoute
  '/solo/perdcomp': typeof SoloPerdcompRoute
  '/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/solo/mensagens/$id': typeof SoloMensagensIdRoute
  '/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/perdcomp/': typeof AuthenticatedPerdcompIndexRoute
  '/solo/mensagens/': typeof SoloMensagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/solo': typeof SoloRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/solo/boas-vindas': typeof SoloBoasVindasRoute
  '/solo/perdcomp': typeof SoloPerdcompRoute
  '/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/solo/mensagens/$id': typeof SoloMensagensIdRoute
  '/mensagens': typeof AuthenticatedMensagensIndexRoute
  '/perdcomp': typeof AuthenticatedPerdcompIndexRoute
  '/solo/mensagens': typeof SoloMensagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/solo': typeof SoloRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/boas-vindas': typeof AuthenticatedBoasVindasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/solo/boas-vindas': typeof SoloBoasVindasRoute
  '/solo/perdcomp': typeof SoloPerdcompRoute
  '/_authenticated/mensagens/$id': typeof AuthenticatedMensagensIdRoute
  '/solo/mensagens/$id': typeof SoloMensagensIdRoute
  '/_authenticated/mensagens/': typeof AuthenticatedMensagensIndexRoute
  '/_authenticated/perdcomp/': typeof AuthenticatedPerdcompIndexRoute
  '/solo/mensagens/': typeof SoloMensagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/solo'
    | '/admin'
    | '/boas-vindas'
    | '/perfil'
    | '/portal'
    | '/solo/boas-vindas'
    | '/solo/perdcomp'
    | '/mensagens/$id'
    | '/solo/mensagens/$id'
    | '/mensagens/'
    | '/perdcomp/'
    | '/solo/mensagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/solo'
    | '/admin'
    | '/boas-vindas'
    | '/perfil'
    | '/portal'
    | '/solo/boas-vindas'
    | '/solo/perdcomp'
    | '/mensagens/$id'
    | '/solo/mensagens/$id'
    | '/mensagens'
    | '/perdcomp'
    | '/solo/mensagens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/solo'
    | '/_authenticated/admin'
    | '/_authenticated/boas-vindas'
    | '/_authenticated/perfil'
    | '/_authenticated/portal'
    | '/solo/boas-vindas'
    | '/solo/perdcomp'
    | '/_authenticated/mensagens/$id'
    | '/solo/mensagens/$id'
    | '/_authenticated/mensagens/'
    | '/_authenticated/perdcomp/'
    | '/solo/mensagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SoloRoute: typeof SoloRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo': {
      id: '/solo'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boas-vindas': {
      id: '/_authenticated/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof AuthenticatedBoasVindasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/solo/boas-vindas': {
      id: '/solo/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/solo/boas-vindas'
      preLoaderRoute: typeof SoloBoasVindasRouteImport
      parentRoute: typeof SoloRoute
    }
    '/solo/perdcomp': {
      id: '/solo/perdcomp'
      path: '/perdcomp'
      fullPath: '/solo/perdcomp'
      preLoaderRoute: typeof SoloPerdcompRouteImport
      parentRoute: typeof SoloRoute
    }
    '/_authenticated/mensagens/': {
      id: '/_authenticated/mensagens/'
      path: '/mensagens'
      fullPath: '/mensagens/'
      preLoaderRoute: typeof AuthenticatedMensagensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens/$id': {
      id: '/_authenticated/mensagens/$id'
      path: '/mensagens/$id'
      fullPath: '/mensagens/$id'
      preLoaderRoute: typeof AuthenticatedMensagensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perdcomp/': {
      id: '/_authenticated/perdcomp/'
      path: '/perdcomp'
      fullPath: '/perdcomp/'
      preLoaderRoute: typeof AuthenticatedPerdcompIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/solo/mensagens/': {
      id: '/solo/mensagens/'
      path: '/mensagens'
      fullPath: '/solo/mensagens/'
      preLoaderRoute: typeof SoloMensagensIndexRouteImport
      parentRoute: typeof SoloRoute
    }
    '/solo/mensagens/$id': {
      id: '/solo/mensagens/$id'
      path: '/mensagens/$id'
      fullPath: '/solo/mensagens/$id'
      preLoaderRoute: typeof SoloMensagensIdRouteImport
      parentRoute: typeof SoloRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBoasVindasRoute: typeof AuthenticatedBoasVindasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
  AuthenticatedMensagensIdRoute: typeof AuthenticatedMensagensIdRoute
  AuthenticatedMensagensIndexRoute: typeof AuthenticatedMensagensIndexRoute
  AuthenticatedPerdcompIndexRoute: typeof AuthenticatedPerdcompIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBoasVindasRoute: AuthenticatedBoasVindasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
  AuthenticatedMensagensIdRoute: AuthenticatedMensagensIdRoute,
  AuthenticatedMensagensIndexRoute: AuthenticatedMensagensIndexRoute,
  AuthenticatedPerdcompIndexRoute: AuthenticatedPerdcompIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface SoloRouteChildren {
  SoloBoasVindasRoute: typeof SoloBoasVindasRoute
  SoloPerdcompRoute: typeof SoloPerdcompRoute
  SoloMensagensIdRoute: typeof SoloMensagensIdRoute
  SoloMensagensIndexRoute: typeof SoloMensagensIndexRoute
}

const SoloRouteChildren: SoloRouteChildren = {
  SoloBoasVindasRoute: SoloBoasVindasRoute,
  SoloPerdcompRoute: SoloPerdcompRoute,
  SoloMensagensIdRoute: SoloMensagensIdRoute,
  SoloMensagensIndexRoute: SoloMensagensIndexRoute,
}

const SoloRouteWithChildren = SoloRoute._addFileChildren(SoloRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SoloRoute: SoloRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
